# assemble a working KE 2.4.3.1

# this is the basic substrate
FROM bdobyns/centos4.6_i386_mysql4_jdk5

# these are the application parts
ADD application/etc.tar.gz /
ADD application/mysql-data.tar.gz /
ADD application/data-krugle.tar.gz /

